---
- name: Cisco ios facts demo
  hosts: device_types_vios
  # gather_facts: false
  connection: network_cli
  vars:
    ansible_network_os: ios
  tasks:
    - name: Gather IOS facts
      cisco.ios.ios_facts:
        gather_subset: all
        available_network_resources: true
        gather_network_resources: l3_interfaces
        
    - name: Print ansible_facts
      ansible.builtin.debug:
        msg:
          - "{{ ansible_facts }}"
