---
- name: Cisco ios facts demo
  hosts: r2
  # gather_facts: false
  tasks:
    - name: Install Package
      ansible.builtin.pip:
        name: ansible-pylibssh
    - name: Gather IOS facts
      cisco.ios.ios_facts:
        gather_subset: all
        available_network_resources: true
        gather_network_resources: l3_interfaces
        
    - name: Print ansible_facts1
      ansible.builtin.debug:
        msg:
          - "{{ ansible_facts }}"

    - name: Config intf
      cisco.ios.ios_l3_interfaces:
        config:
          - name: "{{ interface_name }}"
            ipv4:
              - address: "{{ interface_ip}}"
    # - name: Print ansible_facts
    #   ansible.builtin.debug:
    #     msg:
    #       - "{{ ansible_facts.net_config.split('\n') }}"
