name: learn-github-actions new
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - name: pip3 installs for actions runtime
        # This applies to packages to install in github actions runner/docker image at runtime
        run: pip3 install -r .github/cicd-pip3-requirements.txt

      - name: Install collections required by .ci/tower_conf.yml
        run: ansible-galaxy collection install -r .github/cicd-ansible-collections.yml --force
